name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  uuid: ^4.4.2
  json_annotation: ^4.9.0
  http: ^1.2.2
  shared:
    path: ../shared
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
